name: 'Hugo Build'
description: 'Run a hugo build in a container with all the dependencies'
inputs:
  repoName:
    description: 'The name of the repository without owner'
    required: true
runs:
  using: 'docker'
  image: hugomods/hugo:ci-non-root # kitchen-sink hugo image
  env:
    REPO_NAME: ${{ inputs.repoName }}
    GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
  args:
    - hugo
    - build
    - --minify
    - -b
    - https://${GITHUB_REPOSITORY_OWNER}.github.io/$REPO_NAME/
